export const WEBSITE_HOME = "/"
export const WEBSITE_LOGIN = "/auth/login"
export const WEBSITE_REGISTER = "/auth/register"
export const WEBSITE_RESETPASSWORD = "/auth/reset-password"
export const PRIVACY_POLICY = "/privacy-policy"
export const TERMS_OF_SERVICE = "/terms-of-service"
export const COOKIE_POLICY = "/cookie-policy"

export const USER_DASHBOARD = "/dashboard"
export const NEWS_PAGE = "/news"
